### ISSUE TITLE
null safety conflict with dart test

### ISSUE THREAD

**Issue by wstrange** [dart-lang/convert#42]
The follwing minimum pub spec:
```
name: test_null

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  convert: ^3.0.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.12
```

Causes the version solver to fail with:

```
The current Dart SDK version is 2.12.0-29.10.beta.

Because shelf_static >=0.1.0+1 <0.2.8 requires SDK version >=1.0.0 <2.0.0 or >=2.0.0-dev.55.0 <2.0.0 and no versions of shelf_static match >0.2.8 <0.3.0, shelf_static >=0.1.0+1 <0.2.8-∞ or >0.2.8 <0.3.0 is forbidden.
And because shelf_static 0.2.8 depends on convert >=1.0.0 <3.0.0, shelf_static >=0.1.0+1 <0.3.0 requires convert >=1.0.0 <3.0.0.
Because no versions of test match >1.16.0-nullsafety.12 <2.0.0 and test 1.16.0-nullsafety.12 depends on shelf_static ^0.2.6, test ^1.16.0-nullsafety.12 requires shelf_static ^0.2.6.
Thus, test ^1.16.0-nullsafety.12 requires convert >=1.0.0 <3.0.0.
So, because test_null depends on both convert ^3.0.0-nullsafety.0 and test ^1.16.0-nullsafety.12, version solving failed.
```
